on: [push, workflow_call]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          sudo cat /etc/default/grub
          docker info
          sudo systemctl status docker.service
          sudo cat /lib/systemd/system/docker.service
          ls -l /etc/docker
          sudo cat /etc/docker/*
          echo "user data"
          curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/userData?api-version=2021-01-01&format=text" | base64 --decode
          echo "more info"
          curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute?api-version=2020-09-01"
          ls -l /var/lib/cloud/instance/scripts/
