on: [push, workflow_call]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          docker info
          sudo systemctl status docker.service
          sudo cat /lib/systemd/system/docker.service
          ls /etc/docker
          sudo cat /etc/docker/*
