on: 
  workflow_call:
    inputs:
      HELLO_WORLD:
        type: string
        description: testing
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Input is ${{ inputs.HELLO_WORLD }}"
